### ISSUE TITLE
write EPIPE

### ISSUE THREAD

**Issue by fundon** [jshttp/on-finished#21]
### Koa v2 example

```js
'use string'

var Koa = require('koa')
var app = new Koa()

app.use(({ res }) => {
  res.statusCode = 200
  res.end(JSON.stringify({ hello: 'world' }))
})

app.listen(3000)
```

```console
autocannon -c 100 -d 5 -p 10 localhost:3000
```

```
    at listener (node_modules/on-finished/index.js:170:15)
    at onFinish (node_modules/on-finished/index.js:101:5)
    at callback (node_modules/ee-first/index.js:55:10)
    at Socket.onevent (node_modules/ee-first/index.js:93:5)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at onwriteError (_stream_writable.js:340:10)
    at onwrite (_stream_writable.js:358:5)
    at WritableState.onwrite (_stream_writable.js:89:5)
```

**Comment by dougwilson** [comment]
All this module is doing in your stack trace is forwarding the underlying error Node.js is creating. I don't even see you directly using this module in your example, so if there is a real issue, it should probably be reported to the libraries you are directly using for the authors to track down why it is happening.

I can take a look, but only if you provide an example where you are actually consuming this library in your example, otherwise based on this report, it is FAD.

**Comment by fundon** [comment]
@dougwilson Okay, I updated the example.

```js
var http = require('http')
var onFinished = require('on-finished')

http.createServer(function onRequest(req, res) {
  onFinished(res, function (err) {
    if (err) console.error(err)
  })
  res.statusCode = 200
  res.end(JSON.stringify({ hello: 'world' }))
}).listen(3000)
```

```console
λ ~/D/r/t/server > autocannon -c 100 -d 5 -p 10 localhost:3000
Running 5s test @ http://localhost:3000
100 connections with 10 pipelining factor

Stat         Avg     Stdev    Max
Latency (ms) 11.04   34.05    303
Req/Sec      8901.21 830.63   9671
Bytes/Sec    1.04 MB 94.18 kB 1.18 MB

45k requests in 5s, 5.21 MB read
```

```
{ Error: write EPIPE
    at exports._errnoException (util.js:1026:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:802:14) code: 'EPIPE', errno: 'EPIPE', syscall: 'write' }
{ Error: write EPIPE
    at exports._errnoException (util.js:1026:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:802:14) code: 'EPIPE', errno: 'EPIPE', syscall: 'write' }
{ Error: write EPIPE
    at exports._errnoException (util.js:1026:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:802:14) code: 'EPIPE', errno: 'EPIPE', syscall: 'write' }
{ Error: write EPIPE
    at exports._errnoException (util.js:1026:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:802:14) code: 'EPIPE', errno: 'EPIPE', syscall: 'write' }
{ Error: write EPIPE
    at exports._errnoException (util.js:1026:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:802:14) code: 'EPIPE', errno: 'EPIPE', syscall: 'write' }
{ Error: write EPIPE
    at exports._errnoException (util.js:1026:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:802:14) code: 'EPIPE', errno: 'EPIPE', syscall: 'write' }
{ Error: write EPIPE
    at exports._errnoException (util.js:1026:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:802:14) code: 'EPIPE', errno: 'EPIPE', syscall: 'write' }
{ Error: write EPIPE
    at exports._errnoException (util.js:1026:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:802:14) code: 'EPIPE', errno: 'EPIPE', syscall: 'write' }
{ Error: write EPIPE
    at exports._errnoException (util.js:1026:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:802:14) code: 'EPIPE', errno: 'EPIPE', syscall: 'write' }
```

**Comment by dougwilson** [comment]
Cool, I tried it out and see the same issue. This issue also exists without this module, as the error is being emitted from Node.js core. I'm not clear on what the thoughts are for this module to change

**Comment by fundon** [comment]
Yes, the error from the Node.js core. But nothing report with `wrk -c 100 -t 10 -d 5 http://127.0.0.1:3000` .

/cc @mcollina

**Comment by mcollina** [comment]
@fundon it's actually correct. It depends on the `-p` flag on autocannon, and http pipelining.

**Comment by fundon** [comment]
@mcollina Thanks
